spring:
  profiles:
    active:
      - dog
      - EN
      - qa
guru:
  username: YmlUsername
  password: YmlPassword
  jdbcurl: YmbUrl

---
spring:
  profiles: prod
guru:
  username: ProdUsername
  password: ProdPassword
  jdbcurl: ProdUrl